PASSWORD_MAP = {
    "Michael Scott": "tV3xW5zA",
    "Jim Halpert": "D1eF3gH5iJ",
    "Pam Beesly": "2fG4hI6jK",
    "Dwight Schrute": "F3gH5iJ7kL",
    "Angela Martin": "4hI6jK8lM",
    "Kevin Malone": "gH5iJ7kL9mN",
    "Oscar Martinez": "I6jK8lM0nO",
    "Stanley Hudson": "StanleyChill#7",
    "Phyllis Vance": "PhyllisSale$3",
    "Andy Bernard": "AndySing!11",
    "Kelly Kapoor": "KellySupport@2",
    "Ryan Howard": "RyanTemp!22",
    "Toby Flenderson": "TobyHR#4",
    "Creed Bratton": "CreedQA$5",
    "Meredith Palmer": "MeredithSupplier@6",
    "Darryl Philbin": "DarrylWarehouse#8",
    "Erin Hannon": "PipiDansLeLit123000",
    "Karen Filippelli": "uwuKARENchan456",
    "Nellie Bertram": "NellieIsTheBest789",
    "Bob Vance": "VanceRefrigeration000",
    "Jo Bennett": "JoBossLady111",
    "Hunter": "HunterCoolGuy222",
    "Roy Anderson": "RoyFactoryMan333",
    "Jan Levinson": "JanCorporate444",
    "Gabe Lewis": "GabeNerd555",
}

EMAIL_MAP = {
    "Michael Scott": "michael.scott@dundermifflin.com",
    "Jim Halpert": "jim.halpert@dundermifflin.com",
    "Pam Beesly": "pam.beesly@dundermifflin.com",
    "Dwight Schrute": "dwight.schrute@dundermifflin.com",
    "Angela Martin": "angela.martin@dundermifflin.com",
    "Kevin Malone": "kevin.malone@dundermifflin.com",
    "Oscar Martinez": "oscar.martinez@dundermifflin.com",
    "Stanley Hudson": "stanley.hudson@dundermifflin.com",
    "Phyllis Vance": "phyllis.vance@dundermifflin.com",
    "Andy Bernard": "andy.bernard@dundermifflin.com",
    "Kelly Kapoor": "kelly.kapoor@dundermifflin.com",
    "Ryan Howard": "ryan.howard@dundermifflin.com",
    "Toby Flenderson": "toby.flenderson@dundermifflin.com",
    "Creed Bratton": "creed.bratton@dundermifflin.com",
    "Meredith Palmer": "meredith.palmer@dundermifflin.com",
    "Darryl Philbin": "darryl.philbin@dundermifflin.com",
    "Erin Hannon": "erin.hannon@dundermifflin.com",
    "Karen Filippelli": "karen.filippelli@dundermifflin.com",
    "Nellie Bertram": "nellie.bertram@dundermifflin.com",
    "Bob Vance": "bob.vance@dundermifflin.com",
    "Jo Bennett": "jo.bennett@dundermifflin.com",
    "Hunter": "hunter@dundermifflin.com",
    "Roy Anderson": "roy.anderson@dundermifflin.com",
    "Jan Levinson": "jan.levinson@dundermifflin.com",
    "Gabe Lewis": "gabe.lewis@dundermifflin.com",
}